[general]
import = [
  "~/.config/alacritty/ef-themes/themes/modus-vivendi-tinted.toml"
]

[cursor.style]
shape = "Underline"

[font]
size = 12

[font.normal]
family = "CommitMono"
style = "Regular"

[font.offset]
x = 2
y = 12

[window.dimensions]
columns = 135
lines = 35

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
